name: Build README.md

on:
  push:
  schedule:
    - cron: '0 */12 * * *'
      
jobs:
  build:
    runs-on: macOS-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - name: Install Package Dependencies
      run: |-
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_github('gadenbuie/tweetrmd')"
        Rscript -e "remotes::install_github('rstudio/webshot2')"
        Rscript -e "install.packages('rtweet')"  
    - name: Generate Tweet Screenshot
      env:
        ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      run: |-
        Rscript -e "source('script.R')"
    - name: Commit and push if changed
      run: |-
        git add .
        git commit -m "Updated README"
        git push
